name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: "1.14.3"
    - uses: hashicorp/setup-terraform@v1
      with: 
        terraform_wrapper: false
    - name: terraform validate
      run: terraform init && terraform validate
    - name: Run tests
      run: go test -v ./...
